import { createClient } from "@/lib/supabase/server";
import Link from "next/link";
import { BookOpen, Zap, BarChart2, MessageSquare, ArrowRight, Search } from "lucide-react";
import { MASTER_BOOK_SLUG } from "@/lib/constants";
import { GlobalSearch } from "@/components/global-search";

const FEATURES = [
  {
    icon: Zap,
    title: "AI-Powered Insights",
    description: "Get intelligent summaries, key concepts, and custom quizzes generated by AI for every book.",
  },
  {
    icon: BarChart2,
    title: "Progress Tracking",
    description: "Visualize your reading streaks, time spent, and completion rates across all your books.",
  },
  {
    icon: MessageSquare,
    title: "Chat with Books",
    description: "Ask questions about any chapter and get instant, context-aware answers from our AI.",
  },
];

import { ThemeToggle } from "@/components/theme-toggle";

export default async function LandingPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  let profile = null;
  if (user) {
    const { data } = await supabase.from('profiles').select('avatar_url, full_name').eq('id', user.id).single();
    profile = data;
  }

  return (
    <div className="relative min-h-screen bg-slate-50 dark:bg-black selection:bg-indigo-500/30 overflow-x-hidden flex flex-col">
      {/* ── Navbar ─────────────────────────────────────────────────── */}
      <nav className="fixed top-0 inset-x-0 h-16 sm:h-20 z-[100] bg-white/70 dark:bg-black/70 backdrop-blur-xl border-b border-zinc-200/50 dark:border-zinc-800/50 flex items-center shrink-0">
        <div className="max-w-7xl mx-auto px-6 w-full flex items-center justify-between gap-4">
          <a href="/" className="flex items-center gap-2 sm:gap-3 group focus:outline-none">
            <div className="w-8 h-8 sm:w-10 sm:h-10 rounded-xl bg-indigo-600 flex items-center justify-center text-white shadow-lg shadow-indigo-600/20 rotate-[-5deg] group-hover:rotate-0 transition-transform cursor-pointer">
              <BookOpen size={20} />
            </div>
            <span className="font-black text-lg sm:text-2xl tracking-tight text-zinc-900 dark:text-zinc-50 uppercase italic">Nexus Ai</span>
          </a>

          {/* Functional Search Bar */}
          <div className="hidden lg:flex flex-1 max-w-xl mx-8">
            <GlobalSearch />
          </div>
          
          <div className="flex items-center gap-3 sm:gap-6 ml-auto lg:ml-0">
            <ThemeToggle />
            <div className="w-px h-6 bg-zinc-200 dark:bg-zinc-800 hidden sm:block" />
            
            {user ? (
              <div className="flex items-center gap-3">
                <Link 
                  href={`/reader/${MASTER_BOOK_SLUG}/1`} 
                  className="hidden sm:flex items-center gap-2 px-5 py-2.5 text-sm font-bold text-white bg-indigo-600 hover:bg-indigo-700 rounded-full transition-all shadow-[0_10px_20px_-5px_rgba(79,70,229,0.3)] hover:shadow-[0_15px_30px_-5px_rgba(79,70,229,0.5)] active:scale-95"
                >
                  Continue Journey <ArrowRight size={16} />
                </Link>
                {/* Profile Avatar on the RIGHT */}
                <Link href="/dashboard/settings" className="w-9 h-9 sm:w-11 sm:h-11 rounded-full ring-2 ring-zinc-100 dark:ring-zinc-800 overflow-hidden hover:ring-indigo-500 transition-all flex items-center justify-center bg-zinc-100 dark:bg-zinc-900 group">
                  {profile?.avatar_url ? (
                    <img src={profile.avatar_url} alt="Profile" className="w-full h-full object-cover group-hover:scale-110 transition-transform" />
                  ) : (
                    <span className="text-xs sm:text-sm font-black text-indigo-600 dark:text-indigo-400">
                      {(profile?.full_name || "R")[0].toUpperCase()}
                    </span>
                  )}
                </Link>
              </div>
            ) : (
              <div className="flex items-center gap-2 text-sm font-bold">
                <Link href="/login" className="hidden sm:block text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-white px-4 py-2">Sign In</Link>
                <Link href="/signup" className="px-5 sm:px-6 py-2 sm:py-2.5 bg-zinc-900 dark:bg-white text-white dark:text-zinc-900 rounded-full hover:scale-[1.03] transition-transform shadow-lg">Get Started</Link>
              </div>
            )}
          </div>
        </div>
      </nav>

      {/* ── Hero Section ────────────────────────────────────────────── */}
      <section className="relative flex-1 flex flex-col items-center justify-center pt-32 pb-20 lg:pt-48 lg:pb-32 px-6">
        {/* Glow & Particles */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[300px] h-[300px] sm:w-[600px] sm:h-[600px] bg-indigo-500/10 dark:bg-indigo-500/5 rounded-full blur-[100px] pointer-events-none" />
        
        <div className="relative max-w-5xl mx-auto text-center flex flex-col items-center">
          <div className="inline-flex items-center gap-2.5 px-4 py-2 rounded-full bg-white dark:bg-zinc-900 text-indigo-600 dark:text-indigo-400 text-xs font-black tracking-[.2em] uppercase mb-10 border border-zinc-200 dark:border-zinc-800 shadow-xl animate-in zoom-in-50 duration-1000">
            <span className="w-2 h-2 rounded-full bg-indigo-500 animate-pulse" />
            JUNOR TO SENIOR AI ROADMAP
          </div>

          <h1 className="text-5xl md:text-7xl lg:text-[6rem] font-[1000] tracking-tighter text-zinc-900 dark:text-white leading-[0.95] mb-10 animate-in fade-in slide-in-from-bottom-8 duration-1000 ease-out">
            Master <br className="hidden sm:block" />
            <span className="text-transparent bg-clip-text bg-gradient-to-tr from-indigo-500 via-purple-500 to-pink-500">Agentic Engineering</span>
          </h1>

          <p className="text-base sm:text-lg lg:text-xl text-zinc-500 dark:text-zinc-400 max-w-2xl mb-14 leading-relaxed font-medium animate-in fade-in slide-in-from-bottom-12 duration-1000 delay-200">
            The multi-agent revolution is here. Skip the noise. Start reading the only structured roadmap that takes you from zero to expert.
          </p>

          <div className="flex flex-col sm:flex-row items-center gap-4 w-full sm:w-auto animate-in fade-in slide-in-from-bottom-16 duration-1000 delay-400">
            {user ? (
               <Link 
                 href={`/reader/${MASTER_BOOK_SLUG}/1`} 
                 className="w-full sm:w-auto px-10 py-5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-[2rem] font-black text-xl shadow-[0_20px_40px_-10px_rgba(79,70,229,0.4)] hover:shadow-[0_25px_50px_-10px_rgba(79,70,229,0.6)] hover:-translate-y-1 active:scale-95 transition-all flex items-center justify-center gap-3 group"
               >
                 Resume Journey
                 <ArrowRight size={24} className="group-hover:translate-x-1.5 transition-transform" />
               </Link>
            ) : (
               <>
                 <Link href="/signup" className="w-full sm:w-auto px-10 py-5 bg-zinc-900 dark:bg-white text-white dark:text-zinc-900 rounded-[2rem] font-black text-xl shadow-2xl hover:scale-105 active:scale-95 transition-all text-center">
                   Start Reading FREE
                 </Link>
                 <Link href="/login" className="w-full sm:w-auto px-10 py-5 bg-white dark:bg-zinc-900 text-zinc-900 dark:text-white font-bold text-xl border border-zinc-200 dark:border-zinc-800 rounded-[2rem] hover:bg-zinc-50 dark:hover:bg-zinc-800 transition-all text-center">
                   View Dashboard
                 </Link>
               </>
            )}
          </div>
        </div>
      </section>

      {/* ── Features ───────────────────────────────────────────────── */}
      <section className="py-24 px-6 relative z-10">
        <div className="max-w-7xl mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 sm:gap-12">
            {FEATURES.map((feature, i) => {
              const Icon = feature.icon;
              return (
                <div key={i} className="group flex flex-col p-8 sm:p-10 rounded-[2.5rem] bg-white dark:bg-zinc-900/50 border border-zinc-200 dark:border-zinc-800 hover:border-indigo-500/50 hover:shadow-2xl transition-all duration-500 hover:-translate-y-2 hover:scale-[1.02]">
                  <div className="w-14 h-14 rounded-2xl bg-indigo-50 dark:bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 flex items-center justify-center mb-8 group-hover:scale-110 group-hover:bg-indigo-600 group-hover:text-white transition-all shadow-sm">
                    <Icon size={28} />
                  </div>
                  <h3 className="text-2xl font-black text-zinc-900 dark:text-white mb-4 leading-tight">{feature.title}</h3>
                  <p className="text-zinc-500 dark:text-zinc-400 font-medium leading-relaxed">
                    {feature.description}
                  </p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* ── Footer ─────────────────────────────────────────────────── */}
      <footer className="py-12 px-6 border-t border-zinc-200/50 dark:border-zinc-800/50 text-center shrink-0">
        <div className="flex items-center justify-center gap-2 mb-4 opacity-50">
           <BookOpen size={16} />
           <span className="font-bold text-xs uppercase tracking-widest">NEXUS AI SYSTEM</span>
        </div>
        <p className="text-zinc-500 text-sm font-bold">© {new Date().getFullYear()} Nexus Ai Platform. Built for Autonomous Engineers.</p>
      </footer>
    </div>
  );
}
